### ISSUE TITLE
[BUG]: Syntaxherr Doesn't highlight syntax in existing .asm files

### ISSUE THREAD

**Issue by RickSeiden** [Toeffe3/vscode-asm-syntaxhighlight#10]
Hello,

I'm running VSCode 1.65.2 under Zorin Core Linux 16.0.  I've installed the extension and restarted VSCode.  When I open an existing .asm file that I wrote to compile with vasm oldstyle, nothing is highlighted.

Here's a stupidly simple .asm file that compiles fine under vasm oldstyle:

```
    org $8000

start:
    lda #$FF
    sta $6003
    sta $6001

loop:
    jmp loop:

    org $FFFE
    word start
```
When I open that file, nothing is highlighted.

Is there something I should be doing to get the highlighting?

Thank you,
Rick

**Comment by Toeffe3** [comment]
I cannot reproduce this, make sure that your VSCode assumes that the file extension `.asm` is assembler.
You should not have to do anything the extension should tie `.s`, `.asm` and even `.6502` to the assembler language.
By clicking the language in the right bottom corner you can manually tell VSCode to associate them with assembler if needed.

![image](https://user-images.githubusercontent.com/10633478/158253493-85ccc74e-5103-4714-a286-dbf4679e1a0f.png)


Lastly your current theme might not support any of the extensions highlighting keywords (though directives, instructions and values uses 'standard' keywords (in quotes because there are no standardization)) here the solution is to use the included theme called `VASM (Oldstyle)`.

If this was no help use the command `> Developer: Inspect Editor Tokens and Scopes` to get insight into how the file is processed by the syntax highlighter. When the cursor is in/at a hex value it should say `constant.numeric.hex` and for a label `meta.label` and so fourth for other types.

![image](https://user-images.githubusercontent.com/10633478/158253295-679ea6d8-1002-4506-b260-baa41b821b2b.png)

**Comment by RickSeiden** [comment]
I finally got around to testing it, and this worked perfectly.  Thank you.
